from turtle import *
import math
def PARKIET():
    pu()
    setpos(-420/2,420/2)
    pd()
    ramka_obrazu(420/4/7)
    srodek(420/4/7)

def deska(a):
    fillcolor("darkgreen")
    begin_fill()
    for i in range(2):
        fd(a)
        lt(90)
        fd(6*a)
        lt(90)
    end_fill()

def kwadrat(a):
    ramka(a)
    fd(a)
    lt(90)
    fd(a)
    fillcolor("orange")
    begin_fill()
    rt(90)
    for i in range(4):
        fd(5*a)
        lt(90)
    end_fill()
    zolty_X(a)
    lt(90)
    
def ramka(a):
    for i in range(4):
        deska(a)
        lt(90)
        fd(7*a)
        rt(180)

def ramka_obrazu(a):
    for i in range(4):
        rt(90)
        for i in range(4):
            kwadrat(a)
            rt(90)
            fd(a)
            rt(90)
            fd(a)
            rt(90)
            fd(7*a)
            rt(90)

def zolty_X(a):
    lt(45)
    fillcolor("yellow")
    begin_fill()
    b=(5*a*math.sqrt(2)/2)-a
    fd(b)
    rt(90)
    fd(a)
    rt(90)
    fd(b-a)
    rt(45)
    fd(a*math.sqrt(2))
    end_fill()
    rt(180)
    fd(5*a)
    lt(135)
    fillcolor("yellow")
    begin_fill()
    fd(5*a*math.sqrt(2))
    lt(135)
    fd(a*math.sqrt(2))
    lt(45)
    fd(5*a*math.sqrt(2)-2*a)
    end_fill()
    lt(45)
    fd(a*math.sqrt(2))
    lt(90)
    fillcolor("yellow")
    begin_fill()
    fd(a*math.sqrt(2))
    lt(45)
    fd(5*a*math.sqrt(2)-2*a)
    lt(45)
    fd(a*math.sqrt(2))
    lt(135)
    fd(5*a*math.sqrt(2))
    end_fill()
    lt(135)
    fd(5*a-a*math.sqrt(2))
    fillcolor("yellow")
    begin_fill()
    fd(a*math.sqrt(2))
    lt(135)
    fd((5*a*math.sqrt(2)/2))
    lt(90)
    fd(a)
    lt(90)
    fd(5*a*math.sqrt(2)/2-1*a)
    end_fill()
    lt(45)
    fd(a*math.sqrt(2))
    lt(135)
    begin_fill()
    fd((5*a*math.sqrt(2)/2)-a)
    rt(90)
    fd(a)
    rt(90)
    fd((5*a*math.sqrt(2)/2)-2*a)
    rt(45)
    fd(a*math.sqrt(2))
    end_fill()
    rt(180)
    fd(5*a)
    lt(90)
    fd(5*a)
    lt(135)
    fillcolor("yellow")
    begin_fill()
    fd(5*a*math.sqrt(2)/2)
    lt(90)
    fd(a)
    lt(90)
    fd((5*a*math.sqrt(2)/2)-a)
    lt(45)
    fd(a*math.sqrt(2))
    end_fill()
    
def srodek(a):
    pu()
    setpos(-7*a,-7*a)
    pd()
    kwadrat(a*2)
speed(1)   
PARKIET()
