from turtle import *
import math
global a
a = 20
def kwadrat():
    fillcolor("brown")
    begin_fill()
    setheading(0)
    fd(a)
    lt(90)
    fd(a)
    lt(90)
    fd(a)
    lt(90)
    fd(a)
    end_fill()
    
def jamnik(jak_dlugi):
    setheading(-180)
    fd(a)
    for i in range(2):
        pd()
        kwadrat()
        setheading(0)
        pd()
        fd(a)
    setheading(90)
    pu()
    fd(a)
    lt(45)
    pd()
    fillcolor("brown")
    begin_fill()
    fd(a*math.sqrt(2))
    lt(135)
    fd(a)
    lt(90)
    fd(a)
    end_fill()
    rt(180)
    fd(a)
    lt(90)
    fd(a)
    for i in range(4):
        pd()
        kwadrat()
        setheading(-90)
        pu()
        fd(a)
    rt(180)
    fd(a+a)
    rt(90)
    fd(a)
    for i in range(jak_dlugi):
        pd()
        kwadrat()
        pu()
        setheading(0)
        fd(a)
        pd()
    lt(45)
    fillcolor("brown")
    begin_fill()
    fd(a*math.sqrt(2))
    lt(135)
    fd(a)
    lt(90)
    fd(a)
    end_fill()
    rt(90)
    fd(a)
    lt(90)
    fd(a)
    kwadrat()
    
def ramka():
    pu()
    setpos(-210,-210)
    pd()
    setheading(90)
    fillcolor("yellowgreen")
    begin_fill()
    fd(420)
    rt(90)
    fd(420)
    rt(90)
    fd(420)
    rt(90)
    fd(420)
    end_fill()

  
def RODZINKA():
    ramka()
    pu()
    setpos(-150,-110)
    pd()
    kilka_pieskow(11)
def kilka_pieskow(n):
    for i in range(n+1):
        if i == 5:
            break
        jamnik(n-i)
        setheading(90)
        pu()
        fd(6*a)
        lt(90)
        fd((9-i)*a)
        pd()
speed(0)
RODZINKA()

