tab1 = [0,4,6,1,6]
print("tablica na początku")
print(tab1)

print("--------------")
print("dodam na sam koniec tablicy wartość 7")
tab1.append(7)
print(tab1)
print("--------------")
print("wstawię na index 2 wartość 0")
tab1.insert(2,0)
print("--------------")
print("wstawię na indeks 2 literkę A , przez co wartość 0 przejdzie pod index 3")
tab1.insert(2,"a")
print(tab1)
print("--------------")
print("usunę dany obiekt (6), usuwa tylko jedną 6")
tab1.remove(6)
print(tab1)
print("--------------")
print("sprawdze pod jakim indexem w liście znajdują się wartości 7 i 'a' ")
print(tab1.index(7))
print(tab1.index("a"))