from turtle import *
global a
a = 20
def PALMA():
    pass

def romb(x,kol):
    fillcolor(kol)
    begin_fill()
    y = 360-(2*x)
    rt(x/2)
    fd(a)
    rt(180+y)
    fd(a)
    lt(180+x)
    fd(a)
    rt(180+y)
    fd(a)
    end_fill()
        
def pieniek(x):
    y = 360-(2*x)
    pu()
    setpos(-0,-250)
    pd()
    setheading(90-x)
    rządek(x)
    pu()
    setpos(0,-250)
    pd()
    setheading(90-(x/2))
    fd(a)
    rt(180+60+y)
    fd(a)
    rt(180+x)
    rządek(x)
    pu()
    setpos(0,-250)
    setheading(90+x/2)
    fd(a)
    lt(180+y)
    pd()
    rządek(x)
    pu()
    setpos(0,-250)
    setheading(90-(x/2))
    fd(a)
    pd()
    rządek(x)
    pu()
    setpos(0,-250)
    setheading(0)
    fd(a)
    setheading(90-(x/2))
    fd(a)
    pd()
    rządek(x)
    print(pos())
    
def podstawa(x):
    pu()
    setpos(0,-250)
    pd()
    trojkąt(x)
    rt(180)
    fd(a)
    trojkąt(x)
    fd(2*a)
    trojkąt(x)

def trojkąt(x):
    setheading(90-x/2)
    fillcolor("brown")
    begin_fill()
    fd(a)
    lt(180+x)
    fd(a)
    lt(180+x)
    fd(a)
    end_fill()

def rządek(x):
    y = 360-(2*x)
    setheading(90+90-(x/2))
    for i in range(7):
        romb(x,"brown")
        rt(180+x)
        lt(90)
        rt(x/2)
        fd(a)
        lt(180+y)
        fd(a)
        lt(x/2)

def gora_palmy():
    pu()
    setpos(30.00,9.81)
    pd()
    setheading(90+150)
    fd(a)
    setheading(90-30+90)
    romb(60,"yellowgreen")
    pu()
    setheading(180)
    fd(a)
    rt(60)
    setheading(90-30+90)
    pd()
    romb(60,"yellowgreen")
    setheading(60)
    fd(a)
    lt(90)
    romb(60,"yellowgreen")
    setheading(60)
    fd(a)
    rt(180+120)
    fd(a)
    setheading(60)
    lt(90)
    romb(60,"yellowgreen")
    print(pos())
    
def gałąź_prawa_dolna():
    lt(60)
    fd(a)
    lt(90)
    lt(90)
    for i in range(6):
        romb(60,"yellowgreen")
        lt(180+60)
        fd(a)
        lt(180+120)
        fd(a)
        lt(60)

def gałąź_lewa_dolna():
    pu()
    setpos(30.00,9.81)
    setheading(180)
    fd(2*a)
    rt(120)
    fd(a)
    lt(30)
    pd()
    lt(90)
    print(pos())
    for i in range(6):
        romb(60,"yellowgreen")
        rt(120)
        fd(a)
        rt(60)
        fd(a)
        lt(120)

def gorna_gałąź():
    pu()
    setpos(10.00,79.09)
    lt(60)
    fd(a)
    lt(60)
    fd(a)
    rt(90)
    for i in range(1):
        pd()
        lt(60)
        romb(60,"yellowgreen")
        rt(180)
        fd(a)
        lt(60)
        fd(a)

def liscie():
    pu()
    setpos(10.00,44.45)
    lt(60)
    fd(a)
    lt(60)
    fd(a)
##    rt(30)
    pd()
    romb(60,"yellowgreen")
    print(pos())
    
    
speed(0)
pieniek(60)
podstawa(60)
gora_palmy()
gałąź_prawa_dolna()
gałąź_lewa_dolna()
liscie()
speed(1)

gorna_gałąź()

