from turtle import *
def jeden_krzywulec(x,y,n):
    b = 400/n
    a = b/15
    setpos(x+6*a,y)
    setheading(0)
    fillcolor("darkgreen")
    begin_fill()
    fd(a)
    lt(90)
    fd(4*a)
    lt(90)
    fd(5*a)
    rt(90)
    fd(7*a)
    rt(90)
    fd(5*a)
    lt(90)
    fd(4*a)
    lt(90)
    fd(a)
    lt(90)
    fd(3*a)
    rt(90)
    fd(5*a)
    lt(90)
    fd(9*a)
    lt(90)
    fd(5*a)
    rt(90)
    fd(3*a)
    lt(90)
    fd(a)
    end_fill()

def krzywulec(x,y,n):
    b = 400/n
    a = b/15
    pu()
    setpos(x+8*a,y)
    setheading(0)
    fillcolor("darkgreen")
    begin_fill()
    fd(a)
    lt(90)
    fd(3*a)
    rt(90)
    fd(5*a)
    lt(90)
    fd(9*a)
    lt(90)
    fd(5*a)
    rt(90)
    fd(3*a)
    lt(90)
    fd(a)
    lt(90)
    fd(4*a)
    lt(90)
    fd(5*a)
    rt(90)
    fd(7*a)
    rt(90)
    fd(5*a)
    lt(90)
    fd(3*a)
    end_fill()
    
def gowna_po_bokach(x,y,n):
    b = 400/n
    a = b/15
    pu()
    setpos(x,y+1*a)
    fillcolor("darkgreen")
    begin_fill()
    setheading(0)
    fd(2*a)
    rt(90)
    fd(a)
    lt(90)
    fd(a)
    lt(90)
    fd(2*a)
    lt(90)
    fd(3*a)
    lt(90)
    end_fill()
    pu()
    setpos(x+0,y+13*a)
    setheading(0)
    pd()
    fillcolor("darkgreen")
    begin_fill()
    pd()
    fd(3*a)
    lt(90)
    fd(2*a)
    lt(90)
    fd(a)
    lt(90)
    fd(a)
    rt(90)
    fd(2*a)
    lt(90)
    fd(a)
    end_fill()
    pu()
    setpos(x+12*a,y+15*a)
    setheading(0)
    begin_fill()
    fd(a)
    rt(90)
    fd(a)
    lt(90)
    fd(2*a)
    rt(90)
    fd(a)
    rt(90)
    fd(3*a)
    rt(90)
    fd(2*a)
    end_fill()
    pu()
    setpos(x+12*a,y+0)
    begin_fill()
    setheading(90)
    fd(2*a)
    rt(90)
    fd(3*a)
    rt(90)
    fd(a)
    rt(90)
    fd(2*a)
    lt(90)
    fd(a)
    rt(90)
    fd(a)
    end_fill()
    
#///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

def KAFELKI(n):
    setpos(x,y)
    pd()
    setheading(90)
    fd(3*a)
    kierunek(90)
    fd(5*a)
    kierunek(90)
    rt(180)
    fd(9*a)
    kierunek()
    rt(180)
    fd(4*a)
    kierunek(90)
    fd(3*a)
    rt(90)
    fd(a)
    kierunek(90)
    rt(180)
    fd(4*a)
def dupa(n,x,y):
    b = 400/n
    a = b/15
    gowna_po_bokach(x,y,n)
    pu()
    setpos(x+5*a,y+5*a)
    setheading(0)
    fillcolor("darkgreen")
    begin_fill()
    fd(5*a)
    lt(90)
    fd(5*a)
    lt(90)
    fd(a)
    lt(90)
    fd(4*a)
    rt(90)
    fd(4*a)
    lt(90)
    fd(a)
    end_fill()
    setpos(x+6*a,y+5*a)
    setheading(0)
    begin_fill()
    lt(90)
    fd(4*a)
    rt(90)
    fd(3*a)
    lt(90)
    fd(a)
    lt(90)
    fd(4*a)
    lt(90)
    fd(4*a)
    end_fill()
    for i in range(16):
        setpos(x,y+a*i)
        pd()
        setpos(x+b,y+a*i)
        pu()
        setpos(x,y+a*i)
    for i in range(16):
        pu()
        setpos(x+i*a,y)
        pd()
        setpos(x+i*a,y+b)
    print(a)
speed(0)
def KAFELKI(n):
    b = 400/n
    for j in range(n):
        for i in range(n):
            krzywulec(-200+1*j*b,-200+1*i*b,n)
            jeden_krzywulec(-200+1*b*j,-200+1*i*b,n)
            dupa(n,-200+1*j*b,-200+1*b*i)

pu()
setpos(-200,-200)
KAFELKI(3)
