from turtle import *
import math
global a
a = 20
def KOLUMNY():
    pass
def podstawa():
    pu()
    setpos(-a*11,-150)
    pd()
    setheading(0)
    fd(a*22)
    lt(90)
    fd(a)
    lt(90)
    fd(a*22)
    lt(90)
    fd(a)
    rt(180)
    fd(a)
    rt(90)
    fd(a)
    for i in range(3):
        pd()
        fd(5*a)
        lt(90)
        fd(a/2)
        lt(90)
        fd(5*a)
        lt(90)
        fd(a/2)
        rt(180)
        fd(a/2)
        rt(90)
        fd(a/2)
        lt(90)
        fd(a/2)
        rt(90)
        fd(4*a)
        rt(90)
        fd(a/2)
        rt(180)
        fd(a/2)
        lt(90)
        fd(3*a)
        for i in range(6):
            setheading(90)
            pd()
            fd((22*a/2)-a/2)
            rt(180)
            fd((22*a/2)-a/2)
            lt(90)
            fd(a/2)
            pu()
        setheading(-90)
        fd(a)
        lt(90)
        fd(6*a/2)
        pu()
    setpos(-a*11,-150+22*a/2+3*a)
    pd()
    fd(22*a)
    lt(90)
    fd(a)
    lt(90)
    fd(22*a)
    lt(90)
    fd(a)
    rt(180)
    fd(a)
    rt(45)
    fd(22*a/2*math.sqrt(2))
    rt(90)
    fd(22*a/2*math.sqrt(2))
    rt(45)

speed(0)  
podstawa()
