from turtle import *
import math
def niebieski_kwadrat(ile):
    a = 760 /(ile*3+1)
    color("blue")
    fillcolor("blue")
    begin_fill()
    for i in range(4):
        fd(a)
        lt(90)
    end_fill()

def jedna_koronka(ile):
    a = 760 /(ile*3+1)
    for i in range(3):
        niebieski_kwadrat(ile)
        fd(a)
    lt(90)
    fd(a)
    rt(90)
    niebieski_kwadrat(ile)
    rt(180)
    fd(2*a)
    rt(180)
    for i in range(2):
        niebieski_kwadrat(ile)
        fd(a)
    lt(90)
    fd(a)
    lt(90)
    fd(2*a)
    rt(180)
    niebieski_kwadrat(ile)
    rt(90)
    fd(2*a)
    lt(90)
    fd(a)
    rt(90)
    fd(a)
    lt(90)
    niebieski_kwadrat(ile)
    białe(ile)

def białe(ile):
    a = 760 /(ile*3+1)
    lt(90)
    fd(a)
    rt(90)
    białe_połówki(ile)
    rt(180)
    fd(a)
    rt(90)
    fd(a)
    lt(90)
    białe_połówki(ile)
    rt(180)
    fd(a)
    rt(90)
    fd(a)
    lt(90)
    białe_połówki(ile)
    rt(180)
    fd(a)
    rt(90)
    fd(a)
    lt(90)
    białe_połówki(ile)

def białe_połówki(ile):
    a = 760 /(ile*3+1)
    fillcolor("white")
    begin_fill()
    fd(a)
    lt(135)
    fd(a*math.sqrt(2))
    lt(135)
    fd(a)
    end_fill()

def przejscie(ile):
    a = 760 /(ile*3+1)
    lt(90)
    fd(a)
    lt(90)
    fd(2*a)

def KORONKA(n):
    setpos(-760/2,0)
    for i in range(n):
        jedna_koronka(n)
        przejscie(n)
speed(0)
KORONKA(21)
done()