from turtle import *

def dupa_pandy():
    for i in range(12):
        fd(80)
        rt(30)
    setheading(-150)
    fd(80)
    lt(30)
    fd(80)
    setheading(0)
    pu()
    fd(40)
    lt(60)

def L_oko():
    fillcolor("black")
    begin_fill()
    pd()
    for i in range(6):
        fd(40)
        rt(60)
    end_fill()
    setheading(0)
    fd(40)
    lt(60)
    fd(10)
    rt(60)
    fillcolor("white")
    begin_fill()
    for i in range(6):
        fd(20)
        rt(60)
    end_fill()
    rt(60)
    pu()
    fd(20)
    lt(60)
    lt(60)
    fd(5)
    rt(60)
    pd()
    fillcolor("black")
    begin_fill()
    for i in range(6):
        fd(10)
        rt(60)
    end_fill()

def uszy():
    pass
def nos():
    pu()
    setpos(0,0)
    setheading(0)
    for i in range(6):
        fd(80)
        rt(30)
    rt(60)
    pu()
    fd(80)
    lt(30)
    fillcolor("black")
    begin_fill()
    for i in range(6):
        fd(20)
        rt(60)
    end_fill()
    lt(90)
    fd(2*a)
def P_oko():
    pu()
    setpos(0,0)
    setheading(0)
    fd(80)
    rt(30)
    fd(80)
    setheading(-120)
    fd(40)
    setheading(180)
    pd()
    fillcolor("black")
    begin_fill()
    for i in range(6):
        fd(40)
        lt(60)
    end_fill()
    lt(60)
    fd(40)
    rt(60)
    pu()
    setheading(90)
    fd(10)
    lt(90)
    fd(5)
    pd()
    fillcolor("white")
    begin_fill()
    for i in range(6):
        fd(20)
        lt(60)
    end_fill()
    setheading(-120)
    pu()
    fd(20)
    setheading(90)
    fd(3)
    lt(90)
    fd(3)
    setheading(180)
    fillcolor("black")
    begin_fill()
    for i in range(6):
        fd(10)
        lt(60)
    end_fill()

speed(0)   
dupa_pandy()
L_oko()
P_oko()
nos()
