from turtle import *
global a
a = 20

def nogi(kol):
    kwadrat(kol)
    setheading(-90)
    fd(a)
    kwadrat(kol)

def kwadrat(kol):
    setheading(0)
    fillcolor(kol)
    begin_fill()
    fd(a)
    setheading(90)
    fd(a)
    setheading(180)
    fd(a)
    setheading(-90)
    fd(a)
    end_fill()
    
def srodek(kol):
    pu()
    setpos(-a,0)
    pd()
    nogi(kol)
    pu()
    setpos(0,0)
    pd()
    nogi(kol)
    kwadrat(kol)

def wstążki(kol,x,b):
    setheading(b)
    pd()
    fd(a)
    x(90)
    fd(a)
    nogi(kol)
    for i in range(2):
        setheading(b)
        fd(a)
        x(90)
        fd(a)
        kwadrat(kol)
    pu()
    setpos(0,-a)
def ręczne(kol):
    srodek("green")
    wstążki("green",rt,0)
    setpos(-a,-a)
    wstążki("green",lt,-180)
    pu()
    setpos(-a*2,2*a)
    pd()
    nogi(kol)
    pu()
    setpos(a*1,2*a)
    pd()
    nogi(kol)
    pu()
    setpos(-a,3*a)
    pd()
    setheading(0)
    begin_fill()
    fillcolor(kol)
    kwadrat(kol)
    setheading(0)
    fd(a)
    kwadrat(kol)
def cos(kol):
    pu()
    setpos(2*a,3*a)
    pd()
    kwadrat(kol)
    pu()
    setpos(-3*a,3*a)
    pd()
    kwadrat(kol)
    pu()
    setpos(-3*a,0)
    pd()
    kwadrat(kol)
    pu()
    setpos(2*a,0)
    pd()
    kwadrat(kol)
def kokardy(n):
    pu()
    setpos(2*a,4*a)
    rząd("green",0,n)
    setheading(0)
    fd(a)
    rt(90)
    fd(a)
    kwadrat("green")
    setheading(0)
    fd(a)
    rt(90)
    fd(a)
    nogi("green")
    setheading(180)
    fd(a)
    lt(90)
    fd(a)
    kwadrat("green")
    pu()
    setpos(-3*a,4*a)
    pd()
    rząd("green",-180,n)
    setheading(-90)
    fd(a)
    rt(90)
    fd(a)
    kwadrat("green")
    pu()
    setpos(-3*a,-1*a)
    pd()
    rząd("green",-180,n)
    setheading(90)
    fd(a)
    lt(90)
    fd(a)
    kwadrat("green")
    setheading(90)
    fd(a*2)
    lt(90)
    fd(a)
    setheading(90)
    nogi("green")
    pu()
    setpos(2*a,-a)
    pd()
    rząd("green",0,n)
    pu()
    rt(90)
    fd(2*a)
    lt(90)
    fd(a)
    pd()

def rząd(kol,x,n):
    for i in range(n):
        setheading(x)
        pu()
        fd(a)
        pd()
        kwadrat(kol)

def MUSZKA(n):
    ręczne("green")
    kokardy(n)
    cos("green")
    
speed(0)
MUSZKA(5)
pu()
