from turtle import *
global a
a = 36
def wzorek(n,x,c):
    color("orange")
    pu()
    setpos(0,0)
    setheading(n)
    fd(x)
    rt(90)
    fillcolor("orange")
    begin_fill()
    pd()
    fd(c)
    lt(90)
    fd(a)
    lt(90)
    fd(a)
    rt(90)
    for i in range(5):
        fd(a+1*a*i)
        lt(90)
        fd(a)
        lt(90)
        fd(a+1*a*i)
        rt(90)
        fd(a)
        rt(90)
    end_fill()
def kwadrat():
    pu()
    setpos(0,0)
    setheading(90)
    pd()
    fd(3.5*a)
    fillcolor("orange")
    begin_fill()
    rt(90)
    fd(2.5*a)
    rt(90)
    fd(5*a)
    rt(90)
    fd(5*a)
    rt(90)
    fd(5*a)
    rt(90)
    fd(5*a)
    end_fill()
    
def zygzag():
    wzorek(90,2.5*a,7.5*a)
    wzorek(0,1.5*a,6.5*a)
    wzorek(180,1.5*a,8.5*a)
    wzorek(-90,0.5*a,7.5*a)
    pu()
    kwadrat()
    
speed(0)
zygzag()
