function wac_AFc(a,b){a.tG(b,Date.now())}wac_JS.prototype.I0=wac_5(-2024655713,function(){wac_7k()&&wac_CS(wac_KS(this),{PeopleWell:"PeopleWell"},18)});wac_MS.prototype.I0=wac_5(1241399318,function(){this.pK.I0()});wac_JX.prototype.I0=wac_5(316896117,function(){});wac_40b.prototype.I0=wac_5(-1223737966,function(){this.Mt.I0()});wac_d.Qa.pp.FWd.prototype.T7e=wac_5(-779142581,function(){return this.Suf.T7e()});wac_qWc.prototype.T7e=wac_5(-952640264,function(){return this.Dc.Qb("IsUserProfilePictureResolutionEnabled")});
wac_CL.prototype.Zcf=wac_5(-197263798,function(){this.ra.ma().ff("EditingThumbnailsPanelFocus",!1)});wac_JM.prototype.Zcf=wac_5(936821177,function(){});wac_Nu.prototype.NWe=wac_5(-1606213440,function(){return this.jmg.oj()});wac_Spb.prototype.NWe=wac_5(1521642731,function(){return this.aVf.oj()});wac_Il.prototype.iS=wac_5(-462992048,function(){return this.sg});function wac_z8c(a,b,c){return a.fHe?a.fHe.REd(new Date(b),new Date(c)):-1}function wac_Guc(a,b){return b&&b in a.nAe?a.nAe[b]:null}
function wac_A8c(a){wac_R2c(a);return a.WWc}function wac_H0a(a,b){a.la.wa("RC",b,null)}function wac_B8c(a,b){a.lr|=b}function wac_C8c(a,b){a.Qr=b}function wac_swb(a){return new wac_T_(new wac_wF(a.slideId),a.shapes,a.sn)}window.g_hermesPresenceJS=new Date;Type.registerNamespace("Common.App.CoauthTelemetry");wac_d=window.Common||{};wac_d.Qa=wac_d.Qa||{};wac_d.Qa.t4e=wac_d.Qa.t4e||{};
function wac_D8c(a){this.TXf=Function.createDelegate(this,this.Q8f);this.RYe=Function.createDelegate(this,this.C0e);this.Ndf={};this.Kef={};this.sve=a}
wac_D8c.prototype={bWe:null,sve:null,y6e:null,SLe:wac_a(-1999828422),Gm:function(){if(this.y6e)return this.y6e.oj();this.y6e=new (wac_Rb.$$(Object));var a=this;this.sve.CW(function(){a.bWe=wac_Qb(a.sve);wac_E8c(a.bWe,a.RYe);wac_F8c(a);a.y6e.Ze(null)});return this.y6e.oj()},C0e:function(){wac_F8c(this)},Q8f:function(a,b){return a.dye>b.dye?1:a.dye<b.dye?-1:0}};
function wac_F8c(a){var b=a.bWe.bke();b.sort(a.TXf);a.Ndf={};for(var c=0;c<b.length&&b[c]&&b[c].dye;c++){var d=a,e=b[c].iS(),f=c;a.Ndf[e]=f;e in d.Kef&&(wac_W1a(d.Kef[e],f),delete d.Kef[e])}}
function wac_G8c(a,b,c,d,e,f,g,h,k){this.bjf=Function.createDelegate(this,this.Nof);this.NCf=Function.createDelegate(this,this.Ggg);this.ZSa=a;this.GTe=new (wac_Rb.$$(wac_d.Obf));this.Dc=c;this.Odf=b;this.Uea=d;this.tn=e;this.Lef=f;this.sve=g;this.HNf=h;this.ssf=this.rsf=!1;this.t7e=0;this.urf=1;this.rHc=k;this.WTe=this.Dc.Qb("PeoplesWellExtraButtonInfoIsEnabled")}
wac_G8c.prototype={ZSa:null,GTe:null,Odf:null,Dc:null,Uea:null,tn:null,Lef:null,sve:null,HNf:null,WTe:!1,bWe:null,aOf:null,LQf:null,urf:0,ssf:!1,rsf:!1,t7e:0,rHc:null,Gm:function(){var a=this;wac_Db.WAA.call(null,this.sve,this.Odf,this.Lef).CW(function(){a.bWe=wac_Qb(a.sve);a.aOf=wac_Qb(a.Odf);a.LQf=wac_Qb(a.Lef);wac_Db.WAA.call(null,wac_Qb(a.Odf).mMc(),wac_Qb(a.Lef).OTe.oj()).CW(function(){a.urf=wac_Qb(a.aOf.mMc());a.t7e=wac_Qb(a.LQf.OTe.oj());wac_E8c(a.bWe,a.NCf);a.bWe.bke().length&&a.C0e()})})},
Ggg:function(){this.C0e()},C0e:function(){this.HNf(this.bWe.bke())?(wac_H8c(this.bWe,this.NCf),wac_I8c(this,this.rsf)):wac_W1a(this.GTe,1);this.rsf=!0},Nof:function(){var a=this.tn.Fqa("AppInitStatus_"+wac_d.Qa.Y8a.toString(4));wac_c(42259235,325,!!this.t7e,null);var b=this.t7e-a,c={};c.InteractiveTime=a;c.ReactRenderComplete=this.t7e;c.HadTabSwitch=this.rHc();c.IsModernGallery=this.WTe;wac_b(594883104,325,50,wac_Mgc(c));this.WTe?(wac_b(42062997,325,15,b.toString()),a=this.GTe,c=this.Dc.Ou("CoauthorGalleryTimeToRenderDurationMs",
1E4),c=b>c,this.rHc()?(wac_b(50455714,325,50,c.toString()),b=!1):(c&&(wac_b(42062998,325,15,b.toString()),wac_B().recordQosError("CoauthorGalleryTimeToRenderDurationIsTooLong",["CoauthGalleryExperienceDegraded"],!1,!0,!0,!1,null)),b=c),wac_W1a(a,b?3:2)):wac_b(594883103,325,15,b.toString())}};function wac_J8c(a,b){b?wac_Zg(a.Uea,4,a.bjf,3):wac_W1a(a.GTe,1)}
function wac_I8c(a,b){a.ssf?a.GTe.oj().CW(function(){wac_b(42062996,325,15,"We already attempted to log a render of coauthor gallery: {0}",wac_d.Obf.toString(wac_Qb(a.GTe.oj())))}):(a.ssf=!0,wac_J8c(a,!a.urf&&!b))}function wac_K8c(a,b){this.RYe=Function.createDelegate(this,this.C0e);this.Btf=a;this.NQf=b}function wac_L8c(a){for(var b,c=null,d=a.length,e=0;e<d;++e)if(b=a[e])if(b=b.dmc||!b.wI?b.iS():b.wI.toUpperCase(),!c)c=b;else if(c!==b)return!0;return!1}
wac_K8c.prototype={Oef:null,NQf:null,Btf:null,Gm:function(){var a=this;this.Btf.CW(function(){a.Oef=wac_Qb(a.Btf);wac_E8c(a.Oef,a.RYe)})},C0e:function(){wac_L8c(this.Oef.bke())&&(wac_H8c(this.Oef,this.RYe),this.NQf.IsRealCoauthSession=!0)}};function wac_M8c(){}
wac_M8c.prototype={Ub:function(){return"Common.App.CoauthTelemetry"},gc:function(a){wac_m(wac_n(wac_o(a.fa(wac_K8c,null),wac_ofc)),function(){return new wac_K8c(wac_rP(wac_yta,wac_l(a,wac_yta)),wac_.Gn)});wac_m(wac_n(wac_o(a.fa(wac_G8c,null),wac_$sa)),function(){return new wac_G8c(wac_z(),wac_rP(wac_5ra,wac_l(a,wac_5ra)),wac_.pa,window.Common.App.AppLifecycleManager.get_instance(),wac_Fd(),wac_rP(wac_zta,wac_l(a,wac_zta)),wac_rP(wac_yta,wac_l(a,wac_yta)),wac_L8c,function(){return wac_N8c()})});wac_m(wac_n(wac_o(a.fa(wac_O8c,
null),wac_rfc)),function(){return new wac_O8c(wac_rP(wac_5ra,wac_l(a,wac_5ra)),window.Common.App.AppLifecycleManager.get_instance(),a.H(wac_mfc,null),wac_Fd(),function(){return wac_N8c()},wac_.pa,null,wac_B())});wac_m(wac_n(wac_o(a.fa(wac_D8c,null),wac_mfc)),function(){return new wac_D8c(wac_rP(wac_yta,wac_l(a,wac_yta)))})},Gm:function(){wac_.pa.Ok(function(){wac_j().H(wac_K8c,null).Gm();wac_.pa.Qb("CoauthorGalleryTelemetryIsEnabled")&&wac_j().H(wac_$sa,null).Gm();wac_.pa.Qb("CashTelemetryIsEnabled")&&
(wac_j().H(wac_rfc,null),wac_j().H(wac_mfc,null))})},rc:function(){}};function wac_N8c(){return wac_oda()&&wac_Fd().ota("UserActions")?0<wac_Fd().Fqa("UserActions").VisiToggled:!1}
function wac_O8c(a,b,c,d,e,f,g,h){this.RQf={};this.bUe=new (wac_f.$$(Number))(function(){return f.hWb("PresenceBootLatencyThreshold",1E4)});this.wPe=new (wac_f.$$(Number))(function(){return f.hWb("PresenceBootLatencyCutoffThreshold",6E4)});this.Uea=b;this.OQf=c;this.vrf=a;this.tn=d;this.uQf=g;this.rHc=e;this.az=h;this.Gm()}
wac_O8c.prototype={vrf:null,uQf:null,z6e:null,Uea:null,OQf:null,R5e:null,tn:null,BRf:0,CRf:0,bUe:null,wPe:null,rHc:null,az:null,Gm:function(){if(this.z6e)return this.z6e.oj();this.z6e=new (wac_Rb.$$(Object));this.rHc()&&wac_b(50951700,302,15,"TabSwitched Session");var a=this;this.vrf.CW(function(){var b=wac_Qb(a.vrf),c=b.mMc(),d=b.NWe();d.CW(function(){c.CW(function(){a.az&&a.az.addQosPillar(window.Common.QosPillarName.toString(6));var b=wac_Qb(c),f=wac_Qb(d);a.BRf=b;a.CRf=f?f:(new Date).getTime();
a.z6e.Ze(null)})})});return this.z6e.oj()},SLe:wac_a(-300453624)};function wac_P8c(a,b,c,d,e,f,g,h,k){this._id=a;this.tuf=b;this.SJ=c;this.Def=d;this.mff=e;this.bUe=f;this.wPe=g;this.$Nf=h;this.rHc=k}wac_P8c.prototype={Ww:0,tuf:null,bUe:null,wPe:null,mRf:!1,SJ:0,Def:null,mff:null,$Nf:0,_id:null,rHc:null};window.Common.App.CoauthTelemetry.PL=wac_d.Qa.t4e.Ngg=function(){};wac_d.Qa.t4e.Ngg.prototype={id:null,et:0,st:0,mp:0,tp:0,d:0,ct:null,vc:!1};
wac_D8c.registerClass("Common.App.CoauthTelemetry.CoauthorPositionFinder",null,wac_mfc);wac_G8c.registerClass("Common.App.CoauthTelemetry.CoauthorGalleryTelemetry",null,wac_$sa);wac_K8c.registerClass("Common.App.CoauthTelemetry.CoauthTelemetry",null,wac_ofc);wac_M8c.registerClass("Common.App.CoauthTelemetry.CoauthTelemetryPackage",null,wac_I,wac_i);wac_O8c.registerClass("Common.App.CoauthTelemetry.PresenceBootTelemetry",null,wac_rfc);wac_P8c.registerClass("Common.App.CoauthTelemetry.PresenceLatencyActivityLogger");
window.Common.App.CoauthTelemetry.PL.registerClass("Common.App.CoauthTelemetry.PL");wac_J(wac_C(),new wac_M8c,0);Type.registerNamespace("RealtimePresenceUI");function wac_Nvb(){}wac_Nvb.registerInterface("RealtimePresenceUI.IUserTracker");
function wac_Ovb(a,b,c,d){this.I0f=Function.createDelegate(this,this.Xdg);this.RYe=Function.createDelegate(this,this.C0e);this.OTe=new (wac_Rb.$$(Number));this.dispose=this.rc;this.Ml=a;this.FWd=b;if(c){var e=this;c.CW(function(){e.bWe=wac_Qb(c);wac_E8c(e.bWe,e.RYe);wac_Q8c(e)})}if(d){var f=this;d.CW(function(){f.bse=wac_Qb(d);f.bse.vrg(f.RYe);wac_Q8c(f)})}this.m6d=new wac_Il(this.Ml.sg,"Anonymous user","#cccccc",new wac_Jl(7),null,null,null,null,!1,!1,!1,0,null,0);this.J6a=this.mkb=!0;this.eef=this.Ctf=
!1;this.ZM=wac_nFc(this.Ml.sg,this.Ml.Uyb,a.Fkc)}function wac_Rvb(a,b){return a.lr.lr&1&&b.lr.lr&1||!(a.lr.lr&1||b.lr.lr&1)?a.Qr.localeCompare(b.Qr)-wac_uea:a.lr.lr&1?-1:1}
wac_Ovb.prototype={m6d:null,mkb:!1,Ctf:!1,eef:!1,Ml:null,ZM:null,FWd:null,bWe:null,bse:null,J6a:!1,xJb:function(){return 0<wac_O9(this.ZM)},C0e:function(){if(!this.eef){var a=this;window.setTimeout(function(){wac_Q8c(a);a.eef=!1},3E3);this.eef=!0}},Xdg:function(a,b,c,d,e){wac_W1a(this.OTe,e.RenderTime);return 32},rc:function(){this.bWe&&(wac_H8c(this.bWe,this.RYe),this.bWe=null);this.bse&&(this.bse.Brg(this.RYe),this.bse=null)}};
function wac_Q8c(a){if(!a.Ctf&&(wac_W1a(a.OTe,(new Date).getTime()),wac_b(42567504,325,50,"We are trying to render the coauthor gallery before we are ready to record the render time"),wac_R8c()))return;var b;if(a.rzf)b=a.rzf.bke(!0);else{wac_Y(50440411,814,50,"PowerPointPeoplesWell::GetAllUsersInfo - PeopleInfoProvider is null.");b=[];var c=wac_A8c(a.r9e),d;(d=wac_Tpb(a.hl,a.hl.Zv,{val:void 0}),d)||wac_Y(38589792,814,50,"PowerPointPeoplesWell : GetAllUsersInfo, there is no current editorId:{0} in the editortable",
a.hl.Zv);var e=null;a.qL&&(e=a.qL.wHb());for(var f=wac_.pa.Qb("PeoplesWellExtraButtonInfoIsEnabled"),g=a.hl.u2(),h=g.length,k=0;k<h;++k){var l=g[k];d=a.y1c.YEc(new wac__Hb(l.EmailAddress,null,l.Name,null,!1,null),l.ColorIndex,l.ID,1);var m=new wac_Jl(0);wac_B8c(m,0);var n=0,p=!1;if(e&&l.ID in e){wac_B8c(m,1);if(f){var q=e[l.ID];q&&(n=q.capabilities);p=!0;q&&q.capabilities&4&&wac_B8c(m,4)}delete e[l.ID]}wac_S8c(c,l.EmailAddress)||(Array.add(b,new wac_Il(l.ID,l.Name,d,m,null,l.EmailAddress,null,null,
!1,!1,!1,0,null,0)),wac_Y(8958496,814,50,"PowePointPeoplesWell : GetAllUsersInfo; ClientId: {0}; Color: {1}; PresenceCapabilityHasFlagRealTimeChannel: {2}; PresenceCapabilityHasFlagSupportsChat: {3}; MyClientId: {4}; IsEmailAddressEmpty: {5}; rtcCapabilities:{6}; fIssuserinrtc{7};",l.ID,d,!!(m.lr&1),!!(m.lr&4),a.hl.Zv,!l.EmailAddress,n,p))}if(!f&&a.Eqe&&e)for(var r in e)q=e[r],!wac_S8c(c,q.email)&&q&&q.userName&&(m=new wac_Jl(0),wac_B8c(m,1),q.capabilities&4&&wac_B8c(m,4),f=wac_Guc(a.$sd,q.email)||
q.email,d=a.y1c.YEc(new wac__Hb(f,null,q.userName,null,!1,null),null,q.clientId,1),Array.add(b,new wac_Il(q.clientId,q.userName,d,m,null,f,null,null,!1,!1,!1,0,null,0)),wac_Y(38897818,814,50,"PowePointPeoplesWell : GetAllUsersInfo; Get info from RTC when user is not in editor table and username is provided; ClientId: {0}; Color: {1}; PresenceCapabilityHasFlagRealTimeChannel: {2}; PresenceCapabilityHasFlagSupportsChat: {3}; MyClientId: {4}; IsEmailAddressEmpty: {5}; rtcPresenceCapabilities: {6};",
q.clientId,d,!!(m.lr&1),!!(m.lr&4),a.qL.iS(),!q.email,q.capabilities));0<b.length&&wac_Y(50942294,814,50,"PowerPointPeoplesWell::GetAllUsersInfo - non-empy editor count {0}.",b.length)}b=b||[];c=b.length;for(r=0;r<c;++r)d=b[r],d.iS()||(m=wac_5k().toString(),d.sg=m),d.tpb()||wac_C8c(d,"Anonymous user"),d.lr||(d.lr=new wac_Jl(0)),d.ltc()||d.QTc("#cccccc"),d.dye||(d.dye=0);c=a.ZM;c.fR=new (wac_rb.$$(Array));r=b.length;for(d=0;d<r;++d)if(m=b[d],m.iS()===c.eFb){c.VFb=m;break}r=b.length;for(d=0;d<r;++d)m=
b[d],m.iS()!==c.eFb&&c.suc(m);a.J6a&&1<=wac_O9(a.ZM)&&(wac_b(6092429,325,50,"PeoplesWell: User is no longer forever alone."),a.J6a=!1);a.mkb=!0;wac_R8c()&&a.J6a||wac_Uvb(a)}
function wac_Svb(a){wac_.pa.Qb("CoauthorGalleryTelemetryIsEnabled")&&wac_z().ja(691867605,2147483648,a.I0f);a.Ia.ja(a.Ml.Nf.cxb,1,a.Fdd);a.Ia.jf(a.Ml.Nf.gxb,1,a.Eod,96);a.Ia.jf(a.Ml.Nf.exb,1,a.d7c,96);a.Ia.jf(a.Ml.Nf.dxb,1,a.c7c,96);a.Ia.jf(a.Ml.Nf.fxb,1,a.Cmd,96);a.Ia.ja(a.Ml.Nf.hxb,1,a.gtd);a.Ia.jf(a.Ml.Nf.hjc,1,a.qmd,96);a.Ctf=!0;wac_Q8c(a)}function wac_Yvb(){return wac_.pa&&wac_.pa.Qb("ColorPresenceHashIsEnabled")?"Initials":"Menu32"}
function wac_mmc(){var a;return a=new wac_2l,a.Id="BasicChat",a.Command="2288458806",a.LabelText=CommonUIStrings.l_StartGroupChat,a.LabelCss="display:block; max-width:160px; padding:0px; white-space:normal; word-wrap:break-word",a}
function wac_Zvb(a,b){if(!(b.lr.lr&1))return b.dy()?CommonUIStrings.l_PeoplesWellUserStatusIsViewingOffline:CommonUIStrings.l_PeoplesWellUserStatusLocationUnknown;var c=b.dy(),d=a.Ml.Uyb(b.iS());b=a.Ml.Tyb(b.iS());if(!d)return CommonUIStrings.l_PeoplesWellUserStatusLocationUnknown;switch(d.Sd){case 1:if(b)if(c)a=CommonUIStrings.l_PeoplesWellUserStatusIsViewingOnline;else{var d=null,c=" ",e,f;(f=wac__vb(a,b,e={val:d}),d=e.val,f)&&d&&d.mg&&(a=wac_DI(a.Cc,d.mg))&&(c=String.format(ResourceStrings.l_PeoplesWellUserStatusIsEditingSlide,
a.En+1));a=c||CommonUIStrings.l_PeoplesWellUserStatusLocationUnknown}else a=CommonUIStrings.l_PeoplesWellUserStatusLocationUnknown;return a;case 2:return CommonUIStrings.l_PeoplesWellUserStatusIsInactive;default:return CommonUIStrings.l_PeoplesWellUserStatusLocationUnknown}}
function wac_oFc(a,b,c,d){if(!c)return d&&wac_b(4482393,325,50,"User does not have any presence data"),!1;var e=null,f,g;return(g=wac__vb(a,c,f={val:e}),e=f.val,g)&&e&&e.mg?(a=a.Ml.Uyb(b))&&2===a.Sd?!1:!0:(d&&wac_b(4482394,325,50,"User has presence data but app can't use it"),!1)}function wac_R8c(){return wac_.pa?wac_.pa.Qb("PeoplesWellExtraButtonInfoIsEnabled"):!1}function wac_0vb(a,b,c,d,e){this.Nf=a;this.sg=b;this.Fkc=e;this.Tyb=c||function(){return null};this.Uyb=d||function(){return null}}
function wac_1vb(a,b,c,d){return new wac_0vb(a,b,c,d,!0)}wac_0vb.prototype={Nf:null,ia:function(){return this.Nf.Ab},sg:null,Tyb:null,Uyb:null,Fkc:!1};function wac_2vb(a){this.fR=new (wac_rb.$$(Array));this.eFb=a}wac_2vb.prototype={eFb:null,VFb:null};function wac_3vb(a,b,c){b=b.toUpperCase();var d,e,f;(f=a.fR.qg(b,e={val:d},null),d=e.val,f)||(d=[],a.fR.vf(b,d));Array.add(d,c)}function wac_O9(a){return a.fR.Ma()}
function wac_4vb(a){for(var b=[],c=a.fR.uB().$$ge();c.$$mn();){var d=c.$$cu(),d=a.oDc(d);Array.add(b,d)}return b}function wac_nFc(a,b,c){return c?new wac_Pvb(a,b):new wac_Qvb(a)}function wac_Pvb(a,b){wac_Pvb.initializeBase(this,[a]);this.pKc=b}
wac_Pvb.prototype={pKc:null,suc:function(a){a.dmc||!a.wI?wac_3vb(this,a.iS(),a):this.VFb&&wac_$a().Ka(this.VFb.wI,a.wI)||wac_3vb(this,a.wI,a)},oDc:function(a){for(var b=new Date(0),c=0<a.length?a[0]:null,d=a.length,e=0;e<d;++e){var f=a[e],g=this.pKc(f.sg);g&&b.getTime()<g.fKb.getTime()&&(b=g.fKb,c=f)}return c}};function wac_Qvb(a){wac_Qvb.initializeBase(this,[a])}wac_Qvb.prototype={suc:function(a){wac_3vb(this,a.iS(),a)},oDc:function(a){return a[0]}};
wac_Ovb.registerClass("RealtimePresenceUI.APeoplesWell",null,wac_zta,Sys.IDisposable);wac_0vb.registerClass("RealtimePresenceUI.PeoplesWellSettings");wac_2vb.registerClass("RealtimePresenceUI.UserTracker",null,wac_Nvb);(function(){}).registerClass("RealtimePresenceUI.UserTrackerFactory");wac_Pvb.registerClass("RealtimePresenceUI.UniqueUserTracker",wac_2vb);wac_Qvb.registerClass("RealtimePresenceUI.UserInstanceTracker",wac_2vb);Type.registerNamespace("RealtimePresenceUI");
function wac_L_(a,b,c,d){this.qmd=Function.createDelegate(this,this.GWd);this.gtd=Function.createDelegate(this,this.h5d);this.Cmd=Function.createDelegate(this,this.VWd);this.c7c=Function.createDelegate(this,this.Pzd);this.d7c=Function.createDelegate(this,this.Qzd);this.Eod=Function.createDelegate(this,this.iZd);this.Fdd=Function.createDelegate(this,this.xKd);this.htd=Function.createDelegate(this,this.i5d);this.Dmd=Function.createDelegate(this,this.WWd);this.Fod=Function.createDelegate(this,this.jZd);
wac_L_.initializeBase(this,[a,c,d,null]);this.g1=function(){return!0};this.Ia=b}
wac_L_.prototype={g1:null,Ia:null,jZd:function(a){if(this.mkb){this.J6a||(a[wac_IS.Visible]=!0);var b,c,d,e,f,g=b={val:b},h=c={val:c},k=d={val:d},l=e={val:e},m=f={val:f},n,p,q,r;2<=wac_O9(this.ZM)?r=[String.format(CommonUIStrings.l_PeoplesWellStateNumberOfOtherPeopleEditingHere,wac_O9(this.ZM))]:1===wac_O9(this.ZM)?(n=wac_4vb(this.ZM)[0],r=(p=this.Ml.Uyb(n.iS()))&&2===p.Sd?[CommonUIStrings.l_PeoplesWellStateUserIsInactive,n.tpb()]:[n.dy()?CommonUIStrings.l_PeoplesWellStateUserIsAlsoViewing:CommonUIStrings.l_PeoplesWellStateUserIsAlsoEditing,
n.tpb()]):r=[CommonUIStrings.l_PeoplesWellStateYouAreAllByYourself];wac_O9(this.ZM)?1===wac_O9(this.ZM)?(n=!0,p=this.Ml.Nf.f8a.iKa,q=wac_4vb(this.ZM)[0].ltc()):(n=!0,p=this.Ml.Nf.Apc.iKa,q=""):(n=!1,q=p="");g.val=r[0];h.val=r.slice(1);k.val=n;l.val=p;m.val=q;b=b.val;c=c.val;d=d.val;e=e.val;f=f.val;a[wac_IS.LabelText]=b;c&&c.length&&(a[wac_IS.LabelTextUserGeneratedPlaceholderReplacements]=c);a.ImageIsVisible=d;a[wac_IS.Image16by16Class]=e;a.ImageBackColor=f;this.mkb=!1}return!0},WWd:function(a){if(0>=
wac_O9(this.ZM))a=!1;else{var b=wac_4vb(this.ZM),c=[];Array.addRange(c,b);c.sort(wac_Rvb);for(var b=[],d=c.length,e=0;e<d;++e){var f=c[e],g=String.format("buttonPeoplesWellUser-{0}",f.iS()),h=f.iS(),k=wac_Zvb(this,f),l=f.tpb(),m=f.ltc(),n;n=new wac_w9a;n.Id=g;n.Command=this.Ml.Nf.hxb.toString();n.LabelText="{0}";n.Image32by32=this.Ml.Nf.RCb.Wxb;n.Image32by32Class=this.Ml.Nf.RCb.iKa;n.MenuItemId=h;n.CommandValueId=h;n.Alt=l;n.DisplayMode=wac_Yvb();n.LabelCss="display:block; max-width:160px; padding:0px; white-space:normal; word-wrap:break-word";
n.Description=k;n.ImageBackColor=m;n.IsAnonymous=f.dmc;g=n;if(l=[l],l.length){h=new Sys.StringBuilder("STRARRY@");k=l.length;for(m=0;m<k;++m){var p=l[m];h.append(p?p.length:0);h.append(",");h.append(p);h.append(",")}l=h.toString().slice(0,-1)}else l=null;n=(g.LabelTextUserGeneratedPlaceholderReplacements=l,n.Upn=f.wI,n);wac_.pa.Qb("PeoplesWellExtraButtonInfoIsEnabled")&&this.FWd&&(g=f,g=this.FWd.T7e()?this.FWd.Vbf(g.wI,"O365",wac_.eo,0):void 0,l=this.Ml.Uyb(f.iS()),l=!l||l&&1===l.Sd?!0:!1,n.ImageUrl=
g,n.ActiveStatus=l,n.JoinTimeInMS=f.dye,l=wac_oFc(this,f.iS(),this.Ml.Tyb(f.iS()),!1),f=this.bse?this.bse.Uqg(f.iS()):!!(f.lr.lr&4),n.CanJump=l,n.ChatCapable=f,""===g&&wac_b(40969413,302,50,"ImageURL collection failed"));Array.add(b,n)}var q,c=(q=new wac_if,q.Id="menuCoauthors",q.MaxWidth="220px",q.MenuSectionList=[],q),r;q=(r=new wac_jf,r.Id="msCoauthors",r.ControlsId="msCoauthorsControls",r.DisplayMode=wac_Yvb(),r.ControlList=b,r);wac_.pa.Qb("WordEditorDisplayPeoplesWellLabelIsEnabled")&&this.FWd&&
(q.Title=CommonUIStrings.l_PeoplesWellFlyoutLabel,q.TitleId="menuCoauthorsTitle",q.Theme="Light");Array.add(c.MenuSectionList,q);if(wac_.pa.Qb("DocChatIsEnabled")&&wac_.pa.Qb("PeoplesWellExtraButtonInfoIsEnabled")&&wac_r()&&wac_r().Hd().VN()){r=[];Array.add(r,wac_mmc());var t;r=(t=new wac_jf,t.Id="msGroupChat",t.ControlsId="msGroupChatControl",t.ControlList=r,t);Array.add(c.MenuSectionList,r)}wac_r()&&wac_r().Hd().VN()?a.MenuItems=c:a.PopulationXML=wac_hm(c);a=!0}return a},i5d:function(a){wac_b(4482395,
325,50,"PeoplesWell: Received user button click");var b=a.MenuItemId;if(b){var c=this.Ml.Tyb(b);if(wac_oFc(this,b,c,!0)){a=null;var d,e;(e=wac__vb(this,c,d={val:a}),a=d.val,e)&&a&&a.mg&&(wac_Y(8958488,814,50,"PowerPointPeoplesWell : JumpToUserLocation; clientId: {0}; slideId: {1}; MyClientId: {2};",b,a.mg,this.hl.Zv),(d=wac_DI(this.Cc,a.mg))?(this.Kf.Zcf(),this.Kf.Y$b(d.En)):wac_Y(19191178,814,15,"PowerPointPeoplesWell : JumpToUserLocation; failed to find slide by id: {0}; ",a.mg));a=!0}else a=!1}else a=
!1;return a},cE:function(a,b,c,d,e,f,g){a=!1;switch(c){case 1:a=f(e);break;case 2:a=g(e)}return a?32:8},xKd:function(a,b,c,d,e){var f=this;return this.cE(a,b,c,d,e,function(){return f.xJb()},this.g1)},iZd:function(a,b,c,d,e){return this.cE(a,b,c,d,e,this.Fod,this.g1)},VWd:function(a,b,c,d,e){return this.cE(a,b,c,d,e,this.g1,this.Dmd)},Qzd:function(a,b,c,d,e){return this.cE(a,b,c,d,e,this.g1,this.g1)},Pzd:function(a,b,c,d,e){return this.cE(a,b,c,d,e,this.g1,this.g1)},h5d:function(a,b,c,d,e){return this.cE(a,
b,c,d,e,this.g1,this.htd)},GWd:function(a,b,c,d,e){var f=this;return this.cE(a,b,c,d,e,this.g1,function(){wac_Q8c(f);return!0})},rc:function(){wac_Ovb.prototype.rc.call(this)}};wac_L_.registerClass("RealtimePresenceUI.ABox4PeoplesWell",wac_Ovb);Type.registerNamespace("PowerPointWebEditor");wac_Z=window.PowerPointWebEditor||{};function wac_T8c(a){var b=this;a.uc(function(a){b.s9e=a})}
wac_T8c.prototype={s9e:null,pFd:function(a){return this.s9e?this.s9e.pFd(a):null},rFd:function(a){return this.s9e?this.s9e.rFd(a):null}};Type.registerNamespace("PowerpointPresence");wac_2K=window.PowerpointPresence||{};function wac_U8c(a){this.hl=a}wac_U8c.prototype={hl:null,mMc:function(){return this.hl.mMc()},NWe:function(){return this.hl.NWe()}};
function wac_V8c(a,b,c,d,e){this.Egd=Function.createDelegate(this,this.nPd);this.lAf=new wac_Re;this.hl=a;this.y1c=c;this.gy=d;this.gy.la.xa("ETC",this.Egd);this.HTf=wac_.pa.Qb("PeoplesWellExtraButtonInfoIsEnabled");this.r9e=e;if(b){var f=this;b.uc(function(a){f.qL=a})}}
wac_V8c.prototype={gy:null,hl:null,y1c:null,r9e:null,qL:null,HTf:!1,bke:function(){return this.bke(!1)},bke:function(a){var b=[],c;(c=wac_Tpb(this.hl,this.hl.Zv,{val:void 0}),c)||wac_Y(50440398,814,50,"PeopleInfoProvider::GetAllUsers - current editor({0}) missing in editortable",this.hl.Zv);var d=null;this.qL&&(d=this.qL.wHb());var e=wac_A8c(this.r9e);c=!1;for(var f=this.hl.u2(),g=f.length,h=0;h<g;++h){var k=f[h],l;if(l=a)l=k.EmailAddress,l=!!e&&!!l&&e.toLowerCase()===l.toLowerCase();l?c=!0:Array.add(b,
wac_W8c(this,k,d))}d={};d.fExcludeCurrent=a;d.fCurrentExcluded=c;d.CurrentID=this.hl.Zv;d.EditorCount=this.hl.u2().length;d.IsRtcNull=!this.qL;d.UserCount=b.length;wac_Y(50642948,814,50,"PeopleInfoProvider::GetAllUsers:{0}",wac_ai(d));return b},nPd:function(){wac_Y(50440406,814,50,"PeopleInfoProvider::OnEditorTableUpdate");this.lAf.wa("UsersUpdatedEvent",this,null)}};
function wac_W8c(a,b,c){var d=a.y1c.YEc(new wac__Hb(b.EmailAddress,null,b.Name,null,!1,null),b.ColorIndex,b.ID,1),e=new wac_Jl(0);wac_B8c(e,0);var f=0,g=!1;if(c&&b.ID in c){wac_B8c(e,1);if(a.HTf){var h=c[b.ID];h&&h.capabilities&4&&wac_B8c(e,4);g=!0;h&&(f=h.capabilities)}delete c[b.ID]}wac_Y(50440404,814,50,"PeopleInfoProvider::GetAllUsers; ClientId: {0}; Color: {1}; PresenceCapabilityHasFlagRealTimeChannel: {2}; PresenceCapabilityHasFlagSupportsChat: {3}; MyClientId: {4}; IsEmailAddressEmpty: {5}; rtcCapabilities:{6}; fIssuserinrtc{7};",
b.ID,d,!!(e.lr&1),!!(e.lr&4),a.hl.Zv,!b.EmailAddress,f,g);return new wac_Il(b.ID,b.Name,d,e,null,b.EmailAddress,null,null,!1,!1,!1,b.JoinCoauthTime,null,0)}function wac_H8c(a,b){a.lAf.sb("UsersUpdatedEvent",b)}function wac_E8c(a,b){a.lAf.xa("UsersUpdatedEvent",b)}
function wac_rwb(a,b,c,d,e,f,g,h,k,l,m,n,p,q,r,t,v,u,w){this.Obd=Function.createDelegate(this,this.EHd);this.Umd=Function.createDelegate(this,this.pXd);wac_rwb.initializeBase(this,[a,b,v,w?wac_sP(wac_yta,w):null]);if(!e)throw Error.argumentNull("coauthStateGetter");if(!f)throw Error.argumentNull("appFrame");if(!g)throw Error.argumentNull("taskManager");this.hl=e;this.Ob=f;this.pb=g;if(d){var x=this;d.uc(function(a){x.qL=a})}if(c){var z=this;c.uc(function(a){a.Cmg(z.Umd)})}this.Cc=h;this.Kf=k;this.he=
l;this.ne=p;this.Eqe=q;this.O_a=m;this.y1c=n;this.$sd=r;this.Tob=t;this.r9e=u;this.rzf=w;var y=this;this.OTe.oj().CW(function(){var a=wac_Qb(y.OTe.oj()),b=y.Tob;try{b.OMd||(b.OMd=a,b.tG(17,b.OMd),b.tG(13,wac_z8c(b,wac_02c(b),b.OMd)),wac_W1a(b.rVf,!0))}catch(c){wac_b(594879176,814,10,c.toString())}})}function wac_S8c(a,b){return!!a&&!!b&&a.toLowerCase()===b.toLowerCase()}
wac_rwb.prototype={hl:null,qL:null,Ob:null,pb:null,t6b:!1,Cc:null,Kf:null,he:null,ne:!1,Eqe:!1,O_a:null,y1c:null,$sd:null,Tob:null,r9e:null,rzf:null,pXd:function(){this.Ob.ys().hq?this.t6b||(this.pb.Hb(new wac_D(2,1,0,this.Obd,90,"70",!1,0)),this.t6b=!0):this.Ia.yw(2052777571,2,null)},EHd:function(){this.t6b=!1;this.Ia.yw(2052777571,2,null)},rc:function(){wac_L_.prototype.rc.call(this)}};
function wac_Uvb(a){wac_H0a(a.he,new wac_YL(a.Ml.ia(),!0));var b=1<wac_O9(a.ZM)||1===wac_O9(a.ZM)&&wac_4vb(a.ZM)[0].iS()!==a.Ml.sg;a.ne&&a.O_a.uc(function(c){if(b&&a.Tob){var d=a.Tob;wac_AFc(d,15);0<wac_Z2c(d)&&wac_AFc(d,16)}c.I0()});b&&a.Tob.tG(14,Date.now())}
function wac__vb(a,b,c){c.val=null;if(!b)throw wac_Y(8958490,814,10,"PowerPointPeoplesWell : TryGetPresenceData; Presence was null; MyClientId: {0};",a.hl.Zv),Error.argumentNull("presence");if(!b)return!1;c.val=wac_swb(b.data);return c.val?!0:!1}Type.registerNamespace("PowerPointWebEditor.PeoplesWell");wac_Z.Sgg=wac_Z.Sgg||{};function wac_X8c(){this.xEe=Function.createDelegate(this,this.rMe)}
wac_X8c.prototype={J:null,ZV:null,gy:null,Q8d:null,Ub:function(){return"PowerPointWebEditor.PeoplesWell"},gc:function(a){wac_Y8c=Date.now();this.J=a;this.Q8d=this.J.H(wac_hF,null);this.ZV=this.Q8d.d5c(6,this.Ub());var b=this;wac_m(wac_n(this.J.fa(wac_y2c,null)),function(){return new wac_T8c(wac_l(b.J,wac_z2c))});var c=this;wac_m(wac_n(this.J.fa(wac_5ra,null)),function(){return new wac_U8c(c.J.H(wac_7D,null))});var d=this;wac_m(wac_n(wac_o(this.J.fa(wac_V8c,null),wac_yta)),function(){return new wac_V8c(d.J.H(wac_7D,
null),wac_l(d.J,wac_yc),d.J.H(wac_omc,null),d.J.H(wac_MY,null),d.J.H(wac_L2c,null))});wac_Y(50943688,814,50,"PPTWebEditorPeoplesWellPackage:Configure")},Gm:function(){this.J.H(wac_5ra,null);this.J.H(wac_yta,null);wac_.Q9a.dO()?(this.gy=this.J.H(wac_MY,null),this.gy.la.xa("CSC",this.xEe)):wac_Swb(this)},rMe:function(){try{wac_.Q9a.dO()||(wac_Swb(this),this.gy.la.sb("CSC",this.xEe))}catch(a){wac_Y(8958610,814,10,"PresencePackage::Init; Loading presence and peoples well failed: {0}",a)}},rc:function(){}};
function wac_Z8c(a,b,c,d,e,f,g){var h=a.J.H(wac_Q9,null);h.tG(10,wac_Y8c);h.tG(9,wac__8c);h.tG(11,(new Date).getTime());h=Date.now();b=wac_1vb(new wac_xla("PeoplesWellControl",929022654,3798167515,1285265560,250882013,3236517055,4033456482,2052777571,wac_5h,"per_SingleCollabUserGlyph_16x16x32",wac_5h,"per_SingleCollabUserGlyph_32x32x32",wac_5h,"per_MoreUsersGlyph_16x16x32",null,null),g,b.W$c||(b.W$c=Function.createDelegate(b,b.pFd)),b.Y$c||(b.Y$c=Function.createDelegate(b,b.rFd)));(g=a.J.H(wac_V8c,
null))||wac_Y(50642959,814,10,"InitializePeoplesWellInternal; null PeopleInfoProvider");wac_Y(50943691,814,50,"InitializePeoplesWellInternal; creating peopleswell");var k=new wac_rwb(b,c,wac_l(a.J,wac_SY),wac_l(a.J,wac_yc),a.J.H(wac_7D,null),d,e,a.J.H(wac_Mt,null),a.J.H(wac_hK,null),a.J.H(wac_Qt,null),wac_l(a.J,wac_mr),a.J.H(wac_omc,null),f.K7,f.sne,a.J.H(wac_Huc,null),a.J.H(wac_Q9,null),a.J.H(wac_42,null),a.J.H(wac_L2c,null),g);wac_Svb(k);wac_m(wac_n(wac_o(a.J.fa(wac_rwb,null),wac_zta)),function(){return k});
a.J.H(wac_zta,null);f.K7&&wac_l(a.J,wac_mr).uc(function(a){a.I0()});wac_Y(8958615,814,50,"PresencePackage::InitializePeoplesWell; People's Well loaded and initialized. Time cost: {0}",Date.now()-h);wac_AFc(a.J.H(wac_Q9,null),12)}function wac_Swb(a){var b=a.ZV.saa("peoplewell");wac_Z8c(a,a.J.H(wac_y2c,null),a.J.H(wac_Oc,null),a.J.H(wac_xM,null),a.J.H(wac_dd,null),a.J.H(wac_R,null),a.J.H(wac_X_,null).sg);a.ZV.zaa(b)}wac_T8c.registerClass("PowerPointWebEditor.PresenceUserInfoGetterProxy",null,wac_y2c);
wac_U8c.registerClass("PowerpointPresence.CoauthoringTelemetryInfoProvider",null,wac_5ra);wac_V8c.registerClass("PowerpointPresence.PeopleInfoProvider",null,wac_yta);wac_rwb.registerClass("PowerpointPresence.PowerPointPeoplesWell",wac_L_);wac_X8c.registerClass("PowerPointWebEditor.PeoplesWell.PPTWebEditorPeoplesWellPackage",null,wac_I,wac_i);var wac__8c=0,wac_Y8c=0,wac__8c=Date.now();
if(wac_.pa&&wac_.pa.Qb("IsSyncConfigPresenceEnabled")){var wac_08c=new wac_X8c;wac_08c.gc(wac_j());wac_08c.Gm()}else wac_J(wac_C(),new wac_X8c,0);
