from turtle import *
import math
global a
a = 72/12
print(a)
def posadzka(gowno):
    pass
    
def zasrany_kafelek():
    pu()
    setheading(0)
    fd(8*a)
    lt(90)
    fd(6*a)
    lt(90)
    fd(8*a)
    lt(90)
    fd(6*a)
    setheading(90)
    fd(a)
    rt(45)
    color("darkgreen")
    fillcolor("darkgreen")
    begin_fill()
    fd(2*a*math.sqrt(2))
    lt(90)
    fd(2*a*math.sqrt(2))
    lt(135)
    fd(4*a)
    end_fill()
    fd(a)
    lt(90)
    fd(a)
    lt(45)
    fillcolor("darkgreen")
    begin_fill()
    fd(2*a*math.sqrt(2))
    rt(90)
    fd(a*math.sqrt(2))
    lt(90)
    fd(a*math.sqrt(2))
    rt(90)
    fd(2*a*math.sqrt(2))
    setheading(180)
    fd(6*a)
    end_fill()
    setheading(0)
    fd(7*a)
    lt(90)
    fd(a)
    begin_fill()
    lt(45)
    fd(2*a*math.sqrt(2))
    rt(90)
    fd(2*a*math.sqrt(2))
    setheading(-90)
    fd(4*a)
    end_fill()
    setheading(90)
    fd(5*a)
    lt(90)
    fd(a)
    setheading(-135)
    begin_fill()
    fd(2*a*math.sqrt(2))
    rt(90)
    fd(a*math.sqrt(2))
    lt(90)
    fd(a*math.sqrt(2))
    rt(90)
    fd(2*a*math.sqrt(2))
    setheading(0)
    fd(6*a)
    end_fill()

def rząd(x,y,ile):
    pu()
    setpos(x,y)
    for j in range(ile):
        setpos(x,y+6*a*j)
        for i in range(ile+1):
            zasrany_kafelek()
            setpos(x+8*a*i,y+6*j*a)
            
def ramka(x,y,ile):
    pu()
    setpos(0,0)
    pd()
    setheading(0)
    fd(ile*8*a)
    lt(90)
    fd(ile*6*a)
    lt(90)
    fd(ile*8*a)
    lt(90)
    fd(6*a*ile)
    rząd(x,y,ile)
speed(0)
ramka(0,0,5)
